### PR TITLE
data grid bindings

### PR DESCRIPTION
**Pull request by JaggerJo**

### CODE REVIEW

**Review by JordanMarr — APPROVED** [review]
Very nice! A much needed addition. 👍

**Comment by JaggerJo** [comment]
Yeah, it's about time 😄

The bindings aren't complete yet - somehow the runtime even crashes when double clicking a text cell 😅

Adding the bindings to the current project also means adding a reference to `Avalonia.Controls.DataGrid`.

**Comment by Numpsy** [comment]
> Adding the bindings to the current project also means adding a reference to `Avalonia.Controls.DataGrid`

We do at least seem to be getting to a point where the linker trimming machinery can remove the extra libraries at build time if they aren't actually being called :-)

**Comment by JordanMarr** [comment]
> Yeah, it's about time 😄
> 
> The bindings aren't complete yet - Avalonia even [crashes when double clicking a text cell](https://github.com/AvaloniaUI/Avalonia/issues/10843) 😅

Interesting... it doesn't crash for me when I double click the text cell. 🤷‍♂️

> Adding the bindings to the current project also means adding a reference to `Avalonia.Controls.DataGrid`.

That seems ok to me since the DataGrid is such a commonly used control in most projects.

**Pull request merged**
