### PR TITLE
add funcui templates

### PR DESCRIPTION
**Pull request by AngelMunoz**
Hello everyone, I'm in order to ease releases and reduce the scattered maintenance, I tried to bring the  FuncUI templates into this repo.

This repo includes the following templates
- Counter MVU - `dotnet new funcui.basic.mvu`
- Counter Component - `dotnet new funcui.basic`
- Full Template MVU - `dotnet new funcui.full`

There are a few things I want to add and others to duscuss

### Add
- Full Template Component Version

### Discuss
- Removing Quickstart Template
- Make Component Templates the Default
- Adding a "Tutorial" Template 

For simple purposes I just want to add the Full Template with component version and switch it from draft to free to review that might be tomorrow, for the discuss ones, if you want to discuss in this PR or open an issue about them it would be nice as well

### CODE REVIEW

**Comment by sleepyfran** [comment]
Thanks a lot for taking over this 😃 About the discussion you're suggesting:

- Definitely agree with the removal of the Quickstart template, I think the full template should cover anything that the Quickstart has
- Also agree that the component template should be the default
- What would you put on a tutorial template? A more elaborate example of the basic template we have right now or maybe a commented version of the full template?

**Comment by JaggerJo** [comment]
Nice work!

I think we should also add a x-plat template at some point (desktop, wasm, ios, android).

**Comment by AngelMunoz** [comment]
> What would you put on a tutorial template? A more elaborate example of the basic template we have right now or maybe a commented version of the full template?

I was thinking something along the lines of

```
Step-01-DSL.fs
Step-02-Components.fs
Step-03-MVU.fs
Step-04-Styling.fs
Step-05-Bindings.fs
// any other proposed entry
Entry.fs
Tutorial.fsproj
Styles.axaml
```

it would basically go from explaining the DSL and it's parts (similar to the docs) to showing how to use things, and we could even add a broken file as a "test" to see if the user can "fix" it, that would be a longer task and would be in a separate PR

> I think we should also add a x-plat template at some point (desktop, wasm, ios, android).


Yeah I tried the recent Avalonia xplat template but I had issues running any of the mobile stuff, desktop worked as usual so I'm not sure if we should include it yet

**Comment by AngelMunoz** [comment]
Hey there, I added the FullTemplate with components, and also added readme files with instructions to add fantomas locally (for those using vscode primarily) and a link to the old docs (while we finish doing whatever thing we will do with the docs)

**Review by sleepyfran — APPROVED** [review]
Really awesome job, thanks a lot! :)

**Comment by sleepyfran** [comment]
@AngelMunoz is there anything work left to be done with this or can we get it merged? 😃

**Comment by AngelMunoz** [comment]
Nope, we can merge this further things can be done in different PR's issues

**Comment by sleepyfran** [comment]
So there we go! Thanks a lot @AngelMunoz 😃

**Comment by sleepyfran** [comment]
And they're live! Glad to see the publish thing works well even with new projects 😄 
image

**Pull request merged**
