### PR TITLE
Update to use latest Avalonia.Desktop package.

### PR DESCRIPTION
**Pull request by sandeepc24**

### CODE REVIEW

**Comment by sandeepc24** [comment]
@JaggerJo - Could you please look at this PR?

**Comment by jl0pd** [comment]
I think it's better to use centralized package versions, because in that case we would need to change only 1 file instead of 10. This can be achieved with either `Directory.Build.props` or [`Directory.Packages.props`](https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions) but later is in preview.

**Review by JaggerJo — APPROVED** [review]
LGTM

**Comment by sandeepc24** [comment]
Hi @JaggerJo,  When could you merge the changes? I am looking at using Dialog packages and they need latest version of Avalonia.Desktop.

**Comment by dsyme** [comment]
@JaggerJo Would it be appropriate to ask @sandeepc24 if he would like to be a co-maintainer on this repo?

**Comment by JaggerJo** [comment]
@dsyme Yes, always thankful for some help. @sandeepc24 would you be interested?

**Comment by sandeepc24** [comment]
@dsyme @JaggerJo I'll be happy to help.

**Pull request merged**
