### PR TITLE
Add generic RoutedEvent bindings as Attached Event.

### PR DESCRIPTION
**Pull request by SilkyFowl**
There are times when you want to know the current state of the sender in a RoutedEvent.
This PR adds generic bindings that can be used in such cases.

### CODE REVIEW

**Comment by JaggerJo** [comment]
Nice work!

Could you provide a sample for this?

**Review by SilkyFowl — COMMENTED** [review]
Would it be acceptable if the content is a ported version of the information found on [this page](https://docs.avaloniaui.net/docs/concepts/input/routed-events)?

**Comment by SilkyFowl** [comment]
Samples added.
Please check.

**Review by JaggerJo — APPROVED** [review]
LGTM

**Pull request merged**
