### PR TITLE
Drag and Drop functionality

### PR DESCRIPTION
**Pull request by Numpsy**
This contains the changes from #130 plus

1) It's rebased on top of the current master branch to pick up changes like the DSL code being moved into the main lib and the Elmish v4 updates
2) There's an extra commit to update it to deal with a couple of Avalonia 11 changes

### CODE REVIEW

**Review by JaggerJo — APPROVED** [review]
LGTM

**Comment by JaggerJo** [comment]
LGTM, should I merge?

**Comment by Numpsy** [comment]
The demo in the control catalog does seem to be working ok with the latest code.

(I was previously intending to try adding drop-drop file opening to a tool I was working on that would use this, but I've been snowed under with other things and haven't got to it yet :-( )

**Comment by Numpsy** [comment]
I tried plugging it into a test app and it works sufficiently to open a file via drag and drop, so the base functionality looks good :-)

dragdrop

**Pull request merged**
