### PR TITLE
Run update recursively, until the Cmd.none is returned

### PR DESCRIPTION
**Pull request by Thecentury**

### CODE REVIEW

**Comment by JordanMarr** [comment]
Very nice -- thanks for the update!
Do you have a simple UI example I can use to test this with?

**Comment by Thecentury** [comment]
@JordanMarr I've created two new branches in my fork of the FuncUI.
In both of them, I've updated the `Examples.CounterApp` to use the elmish hook. The changes are aimed at adding the following behaviour:
- if `Increment` is invoked when the counter is equal to 5, the value is reset instead by returning the `Cmd.ofMsg Reset` from the `Increment` message handler.
- If `Reset` is called an even number of times, it resets not to 0 but to 1 by returning `Cmd.ofMsg Increment`.
The rules are pretty artificial but reproduce the problem.

The first branch, `cmd-ofmsg-ignored` (https://github.com/Thecentury/Avalonia.FuncUI/blob/cmd-ofmsg-ignored/src/Examples/Component%20Examples/Examples.CounterApp/Main.fs), is based on the current master so the second message (`Increment` produced from the `Reset` handler) is ignored and therefore even iterations of `Reset` produce counter equals to 0 (and not to expected 1).
The second branch, `cmd-ofmsg-is-not-ignored` (https://github.com/Thecentury/Avalonia.FuncUI/blob/cmd-ofmsg-is-not-ignored/src/Examples/Component%20Examples/Examples.CounterApp/Main.fs) is based on the branch of the fix. The `Increment` produced from the `Reset` handler is not ignored, so even iterations of `Reset` produce counter = 1.

Please let me know if you'd like to have anything else in these sample programs.

**Comment by JordanMarr** [comment]
Ok, I see the issue now. It was a naive implementation, so thank you for improving it.

Btw, I got a little confused debugging your example, so I changed it to this:

```F#
module Main =
    open Avalonia.Controls
    open Avalonia.FuncUI
    open Avalonia.FuncUI.DSL
    open Avalonia.Layout
    open Avalonia.FuncUI.Elmish.ElmishHook

    type Model = { Count: int }
    type Msg =
        | Increment
        | Decrement
        | Reset
        | Output of string
        
    let init = { Count = 0 }, Cmd.none
    
    let update msg model =
        match msg with
        | Increment ->
            let model = { model with Count = model.Count + 1 }
            if model.Count >= 5
            then model, Cmd.ofMsg Reset
            else model, Cmd.none
        | Decrement -> { model with Count = model.Count - 1 }, Cmd.none
        | Reset ->
            { model with Count = 0 }, Cmd.ofMsg (Output "Resetting")
        | Output msg -> 
            printfn "OUPUT: %s" msg
            model, Cmd.none

    let view =
        Component
            (fun ctx ->
                let model, dispatch = ctx.useElmish (init, update)

                DockPanel.create [
                    DockPanel.children [
                        Button.create [
                            Button.dock Dock.Bottom
                            Button.onClick (fun _ -> dispatch Reset)
                            Button.content "reset"
                            Button.horizontalAlignment HorizontalAlignment.Stretch
                        ]
                        Button.create [
                            Button.dock Dock.Bottom
                            Button.onClick (fun _ -> dispatch Decrement)
                            Button.content "-"
                            Button.horizontalAlignment HorizontalAlignment.Stretch
                        ]
                        Button.create [
                            Button.dock Dock.Bottom
                            Button.onClick (fun _ -> dispatch Increment)
                            Button.content "+"
                            Button.horizontalAlignment HorizontalAlignment.Stretch
                        ]
                        TextBlock.create [
                            TextBlock.dock Dock.Top
                            TextBlock.fontSize 48.0
                            TextBlock.verticalAlignment VerticalAlignment.Center
                            TextBlock.horizontalAlignment HorizontalAlignment.Center
                            TextBlock.text (string model.Count)
                        ]
                    ]
                ])
```

**Review by JordanMarr — APPROVED** [review]
Looks great. Thank you!

**Pull request merged**
