### PR TITLE
Allow IComponentContext.useElmish with supplied mapProgram to change msg type

### PR DESCRIPTION
**Pull request by marklam**
From a question I raised in https://github.com/fsprojects/Avalonia.FuncUI/discussions/339

It's possible to change the msg type if the useElmish method is split into overloads which take / don't take mapProgram - rather than an optional parameter which defaults to `id`

I've added the somewhat pointless `withTimings` to the Chord Parser app just to demonstrate it working.

If you'd rather not merge it, I have a workaround which sits outside Avalonia.FuncUI, but I thought I'd offer it up anyway.

### CODE REVIEW

**Comment by JaggerJo** [comment]
@JordanMarr could you take a look?

**Comment by JordanMarr** [comment]
I'm not sure that implementation will handle the scenario where you map other things, like the view or the model.
I will kick it around a bit and see if I can come up with a solution.

**Comment by JordanMarr** [comment]
I have to admit that I still don't fully understand your use case, but it seems very specific to your project. (It doesn't help that I could find no examples of `Program.map` in the wild to help inform my intuition on how it is commonly used.)
My gut feeling is that it's not a feature that will be needed by others, and so I don't think the added complexity is worth it. Especially considering that fact that you can easily create your own extensions methods within your project (as you have probably done).

**Comment by edgarfgp** [comment]
Looks similar to what we have in Fabulous that allows to map a `CmdMsg` into a regular `Msg` 🤔https://github.com/fabulous-dev/Fabulous.Avalonia/blob/b32481fe7d6d3cc62ca9501656a919d6c8228701/src/Fabulous.Avalonia/Program.fs#L109

**Comment by marklam** [comment]
That's fair. I found a way round it in about the same amount of code.  

I'll close this PR and maybe comment my workaround in the linked discussion when I get a moment.

**Comment by JordanMarr** [comment]
After experimenting with it, I have something that I could live with, but it works slightly differently than what you had.
The difference would be that it returns a `dispatch: (TimedMsg -> unit)`, so you would still need to map the `Msg`:

```F#
let view () = Component (fun ctx ->
    let model, dispatch = ctx.useElmish(init, update,  Program.withSubscription subscriptions >> withTimings)
    let dispatch = TimedMsg.map >> dispatch
```

```F#
type TimedMsg = { Time: DateTime; Message: Msg } with
    static member map msg = { Time = DateTime.UtcNow; Message = msg }
```

The implementation is here: 
https://github.com/fsprojects/Avalonia.FuncUI/compare/master...JordanMarr:Avalonia.FuncUI:elmish-hook-map-program

Would that be flexible enough to work for your situation?

**Comment by marklam** [comment]
Yes, I think that would work ok.

**Pull request closed without merging**
